name: Daily QR Report

on:
  schedule:
    - cron: '0 13 * * *'  # Runs every day at 6 AM PST (13:00 UTC)
  workflow_dispatch:

jobs:
  send-daily-report:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Edge Function
        env:
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          curl -X POST "https://dkrpawmussqqbjlrvasz.supabase.co/functions/v1/send-daily-reports?token=${CRON_SECRET}"
